## You should change each of the following fields
## to customize your blog

title: STAT 386 Blog
description: "This blog was created to make blog posts for my STAT 386 class." 
author: Darian Dyer
author_description: "I am a statistics major at Brigham Young University." 

url: https://darianrd.github.io ## change this to https://yourusername.github.io
baseurl: /StatBlog ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  darianrd
    email:   dyerdarian2@gmail.com



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




